#Main Sconscript for the ---xos--- module
# An experimental build system used at LBNL (Nick Sauter) to compile the SSRL
# packages for WebIce.  Build tools include SCons & cctbx, not gmake.

import libtbx.load_env
import os
Import("env_base", "env_etc")

env_etc.xos_dist = libtbx.env.dist_path("xos")

env_etc.xos_include = env_etc.norm_join(env_etc.xos_dist,"src")

env_xos = env_base.Copy(
  LIBS = env_etc.libm + ["rt","pthread","mach","exc","c"]
)

arch_dependent_flags={"irix_CC":["-DIRIX","-DPTHREADS","-MP:dsm=off"],
		      "unix_gcc":["-DLINUX","-fexceptions","-pthread","-fPIC"],
                      "tru64_cxx":["-DDEC_UNIX","-pthread"]}

env_xos.Append(
CCFLAGS=["-c","-D_REENTRANT"]+arch_dependent_flags[env_etc.compiler])

env_xos.Append(LIBPATH=["#lib",])

lib_xos_sources = [
  "src/xos.c",
  "src/xos_hash.c",
  "src/xos_semaphore_set.c",
  "src/xos_socket.c",
  "src/xos_http.c",
  "src/xos_log.c",
]

builder = env_xos.StaticLibrary
builder(
    target="#lib/xos",
    source=lib_xos_sources)
