# Tcl package index file, version 1.0
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

set ext [info sharedlibextension]
package ifneeded DvmBasic 1.0 [list load $dir/tclDvmBasic$ext]
package ifneeded DvmMpeg 1.0 [list load $dir/tclDvmMpeg$ext]
package ifneeded DvmPnm 1.0 [list load $dir/tclDvmPnm$ext]
package ifneeded DvmAmap 1.0 [list load $dir/tclDvmAmap$ext]
package ifneeded DvmImap 1.0 [list load $dir/tclDvmImap$ext]
package ifneeded DvmVision 1.0 [list load $dir/tclDvmVision$ext]
package ifneeded DvmColor 1.0 [list load $dir/tclDvmColor$ext]
package ifneeded DvmByteGeom 1.0 [list load $dir/tclDvmByteGeom$ext]
package ifneeded DvmGif 1.0 [list load $dir/tclDvmGif$ext]
package ifneeded DvmKernel 1.0 [list load $dir/tclDvmKernel$ext]
package ifneeded DvmJpeg 1.0 [list load $dir/tclDvmJpeg$ext]
package ifneeded DvmVision 1.0 [list load $dir/tclDvmVision$ext]
package ifneeded DvmWave 1.0 [list load $dir/tclDvmWave$ext]
