echo Setting CLASSPATH...
CLASSPATH=/home/penjitk/software/junit3.8.1/junit.jar:/home/penjitk/software/httpunit-1.5.3/lib/httpunit.jar:$CLASSPATH
export CLASSPATH
echo CLASSPATH env is now $CLASSPATH
echo Environment ready for junit tests...
