-- Version name --
insert into VERSION_INFO(VERSION_NAME) values ('DEVELOPMENT');

-- Add users --
insert into USER_INFO(USER_ID, LOGIN_NAME, REAL_NAME, UPLOAD_TEMPLATE) values (1, 'annikas', 'Annika Sorenstam', 'ssrl');
insert into USER_INFO(USER_ID, LOGIN_NAME, REAL_NAME, UPLOAD_TEMPLATE) values (2, 'tigerw', 'Tiger Woods', 'jcsg');
insert into USER_INFO(USER_ID, LOGIN_NAME, REAL_NAME, UPLOAD_TEMPLATE) values (3, 'lorenao', 'Lorena Ochoa', 'als');
insert into USER_INFO(USER_ID, LOGIN_NAME, REAL_NAME, UPLOAD_TEMPLATE) values (4, 'sergiog', 'Sergio Garcia', 'ssrl');

-- Add sils --
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME, SIL_LOCKED, SIL_KEY) select 1, USER_ID, 'sil1.xls', '2008-01-12 16:06:50', '1', 'ABCDEF' from USER_INFO where USER_INFO.LOGIN_NAME = 'annikas';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME, SIL_LOCKED) select 2, USER_ID, 'sil2.xls', '2008-10-21 08:40:32', '1'  from USER_INFO where USER_INFO.LOGIN_NAME = 'annikas';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 3, USER_ID, 'sil3.xls', '2008-10-21 20:22:13' from USER_INFO where USER_INFO.LOGIN_NAME = 'annikas';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 4, USER_ID, 'jcsg_sil1.xls', '2008-12-31 23:45:58' from USER_INFO where USER_INFO.LOGIN_NAME = 'tigerw';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 5, USER_ID, 'jcsg_sil2.xls', '2009-01-01 06:10:54' from USER_INFO where USER_INFO.LOGIN_NAME = 'tigerw';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 6, USER_ID, 'jcsg_sil3.xls', '2009-01-13 13:28:31' from USER_INFO where USER_INFO.LOGIN_NAME = 'tigerw';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 7, USER_ID, 'als_sil1.xls', '2009-02-01 05:41:26' from USER_INFO where USER_INFO.LOGIN_NAME = 'lorenao';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 8, USER_ID, 'als_sil2.xls', '2009-02-01 22:49:22' from USER_INFO where USER_INFO.LOGIN_NAME = 'lorenao';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 9, USER_ID, 'als_sil3.xls', '2009-05-30 10:11:43' from USER_INFO where USER_INFO.LOGIN_NAME = 'lorenao';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 10, USER_ID, 'als_sil4.xls', '2009-06-05 11:40:01' from USER_INFO where USER_INFO.LOGIN_NAME = 'lorenao';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME, SIL_LOCKED, SIL_KEY) select 11, USER_ID, 'sergiog_sil1.xls', '2009-07-19 18:03:57', '1', 'HIJKLM' from USER_INFO where USER_INFO.LOGIN_NAME = 'sergiog';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME, SIL_LOCKED) select 12, USER_ID, 'sergiog_sil2.xls', '2009-07-19 23:44:36', '1' from USER_INFO where USER_INFO.LOGIN_NAME = 'sergiog';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME, SIL_LOCKED) select 13, USER_ID, 'sergiog_sil3.xls', '2009-07-25 08:34:25', '1' from USER_INFO where USER_INFO.LOGIN_NAME = 'sergiog';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 14, USER_ID, 'sergiog_sil4.xls', '2009-07-29 14:51:08' from USER_INFO where USER_INFO.LOGIN_NAME = 'sergiog';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 15, USER_ID, 'sil4.xls', '2009-08-06 11:32:16' from USER_INFO where USER_INFO.LOGIN_NAME = 'annikas';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 16, USER_ID, 'sil5.xls', '2009-08-15 19:01:01' from USER_INFO where USER_INFO.LOGIN_NAME = 'annikas';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME, SIL_LOCKED) select 17, USER_ID, 'sil6.xls', '2009-08-18 09:31:58', '1' from USER_INFO where USER_INFO.LOGIN_NAME = 'annikas';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 18, USER_ID, 'sil7.xls', '2009-09-21 12:45:17' from USER_INFO where USER_INFO.LOGIN_NAME = 'annikas';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME, SIL_LOCKED, SIL_KEY) select 19, USER_ID, 'sil8.xls', '2009-09-21 18:29:09', '1', 'XYZ123' from USER_INFO where USER_INFO.LOGIN_NAME = 'annikas';
insert into SIL_INFO(SIL_ID, USER_ID, UPLOAD_FILENAME, UPLOAD_TIME) select 20, USER_ID, 'sergiog_sil5.xls', '2009-10-03 16:12:27' from USER_INFO where USER_INFO.LOGIN_NAME = 'sergiog';

-- Add beamlines --
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (1, 'BL1-5', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (2, 'BL1-5', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (3, 'BL1-5', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (4, 'BL1-5', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (5, 'BL7-1', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (6, 'BL7-1', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (7, 'BL7-1', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (8, 'BL7-1', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (9, 'BL9-1', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (10, 'BL9-1', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (11, 'BL9-1', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (12, 'BL9-1', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (13, 'BL9-2', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (14, 'BL9-2', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (15, 'BL9-2', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (16, 'BL9-2', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (17, 'BL11-1', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (18, 'BL11-1', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (19, 'BL11-1', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (20, 'BL11-1', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (21, 'BL11-3', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (22, 'BL11-3', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (23, 'BL11-3', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (24, 'BL11-3', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (25, 'BL12-2', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (26, 'BL12-2', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (27, 'BL12-2', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (28, 'BL12-2', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (29, 'BL14-1', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (30, 'BL14-1', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (31, 'BL14-1', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (32, 'BL14-1', 'right');

-- Assign sils to beamlines --
update BEAMLINE_INFO set SIL_ID = 1 where BEAMLINE_NAME = 'BL1-5' and BEAMLINE_POSITION = 'left';
update BEAMLINE_INFO set SIL_ID = 3 where BEAMLINE_NAME = 'BL1-5' and BEAMLINE_POSITION = 'right';
update BEAMLINE_INFO set SIL_ID = 4 where BEAMLINE_NAME = 'BL7-1' and BEAMLINE_POSITION = 'middle';
update BEAMLINE_INFO set SIL_ID = 13 where BEAMLINE_NAME = 'BL7-1' and BEAMLINE_POSITION = 'right';
update BEAMLINE_INFO set SIL_ID = 20 where BEAMLINE_NAME = 'BL7-1' and BEAMLINE_POSITION = 'left';
update BEAMLINE_INFO set SIL_ID = 5 where BEAMLINE_NAME = 'BL9-1' and BEAMLINE_POSITION = 'left';
update BEAMLINE_INFO set SIL_ID = 2 where BEAMLINE_NAME = 'BL9-1' and BEAMLINE_POSITION = 'middle';
update BEAMLINE_INFO set SIL_ID = 7 where BEAMLINE_NAME = 'BL9-1' and BEAMLINE_POSITION = 'right';
update BEAMLINE_INFO set SIL_ID = 6 where BEAMLINE_NAME = 'BL9-2' and BEAMLINE_POSITION = 'left';
update BEAMLINE_INFO set SIL_ID = 8 where BEAMLINE_NAME = 'BL11-1' and BEAMLINE_POSITION = 'left';
update BEAMLINE_INFO set SIL_ID = 9 where BEAMLINE_NAME = 'BL12-2' and BEAMLINE_POSITION = 'middle';
update BEAMLINE_INFO set SIL_ID = 11 where BEAMLINE_NAME = 'BL12-2' and BEAMLINE_POSITION = 'left';
update BEAMLINE_INFO set SIL_ID = 14 where BEAMLINE_NAME = 'BL14-1' and BEAMLINE_POSITION = 'left';
update BEAMLINE_INFO set SIL_ID = 18 where BEAMLINE_NAME = 'BL14-1' and BEAMLINE_POSITION = 'middle';
update BEAMLINE_INFO set SIL_ID = 19 where BEAMLINE_NAME = 'BL14-1' and BEAMLINE_POSITION = 'right';

-- Last uniqueId for crystal. There must be only one row in this table --
insert into CRYSTAL_INFO(LAST_UNIQUE_ID) values (3000000);

ALTER SEQUENCE USER_INFO_SEQUENCE RESTART WITH 5;
ALTER SEQUENCE SIL_INFO_SEQUENCE RESTART WITH 21;
ALTER SEQUENCE BEAMLINE_INFO_SEQUENCE RESTART WITH 33;
