-- Version name --
insert into VERSION_INFO(VERSION_NAME) values ('DEVELOPMENT');

-- Add users --
insert into USER_INFO(USER_ID, LOGIN_NAME, REAL_NAME, UPLOAD_TEMPLATE) values (1, 'annikas', 'Annika Sorenstam', 'ssrl');
insert into USER_INFO(USER_ID, LOGIN_NAME, REAL_NAME, UPLOAD_TEMPLATE) values (2, 'tigerw', 'Tiger Woods', 'jcsg');
insert into USER_INFO(USER_ID, LOGIN_NAME, REAL_NAME, UPLOAD_TEMPLATE) values (3, 'lorenao', 'Lorena Ochoa', 'als');
insert into USER_INFO(USER_ID, LOGIN_NAME, REAL_NAME, UPLOAD_TEMPLATE) values (4, 'sergiog', 'Sergio Garcia', 'ssrl');

-- Add beamlines --
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (1, 'BL1-5', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (2, 'BL1-5', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (3, 'BL1-5', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (4, 'BL1-5', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (5, 'BL7-1', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (6, 'BL7-1', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (7, 'BL7-1', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (8, 'BL7-1', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (9, 'BL9-1', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (10, 'BL9-1', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (11, 'BL9-1', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (12, 'BL9-1', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (13, 'BL9-2', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (14, 'BL9-2', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (15, 'BL9-2', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (16, 'BL9-2', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (17, 'BL11-1', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (18, 'BL11-1', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (19, 'BL11-1', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (20, 'BL11-1', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (21, 'BL11-3', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (22, 'BL11-3', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (23, 'BL11-3', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (24, 'BL11-3', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (25, 'BL12-2', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (26, 'BL12-2', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (27, 'BL12-2', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (28, 'BL12-2', 'right');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (29, 'BL14-1', 'no cassette');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (30, 'BL14-1', 'left');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (31, 'BL14-1', 'middle');
insert into BEAMLINE_INFO(BEAMLINE_ID, BEAMLINE_NAME, BEAMLINE_POSITION) values (32, 'BL14-1', 'right');

-- Last uniqueId for crystal. There must be only one row in this table --
insert into CRYSTAL_INFO(LAST_UNIQUE_ID) values (1);

ALTER SEQUENCE USER_INFO_SEQUENCE RESTART WITH 1;
ALTER SEQUENCE SIL_INFO_SEQUENCE RESTART WITH 1;
ALTER SEQUENCE BEAMLINE_INFO_SEQUENCE RESTART WITH 33;
