-- Version name --
insert into VERSION_INFO(VERSION_NAME) values ('PRODUCTION');

-- Add beamlines --
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL1-5', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL1-5', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL1-5', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL1-5', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL7-1', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL7-1', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL7-1', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL7-1', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL9-1', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL9-1', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL9-1', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL9-1', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL9-2', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL9-2', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL9-2', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL9-2', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL11-1', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL11-1', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL11-1', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL11-1', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL11-3', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL11-3', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL11-3', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL11-3', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL12-2', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL12-2', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL12-2', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL12-2', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL14-1', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL14-1', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL14-1', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL14-1', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL-sim', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL-sim', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL-sim', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('BL-sim', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM1-5', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM1-5', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM1-5', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM1-5', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM7-1', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM7-1', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM7-1', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM7-1', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM9-1', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM9-1', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM9-1', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM9-1', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM9-2', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM9-2', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM9-2', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM9-2', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM11-1', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM11-1', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM11-1', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM11-1', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM11-3', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM11-3', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM11-3', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM11-3', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM12-2', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM12-2', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM12-2', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM12-2', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM14-1', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM14-1', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM14-1', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('SIM14-1', "right");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('X4_simple1', "no cassette");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('X4_simple1', "left");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('X4_simple1', "middle");
insert into BEAMLINE_INFO(BEAMLINE_NAME, BEAMLINE_POSITION) values ('X4_simple1', "right");

-- Last uniqueId for crystal. There must be only one row in this table --
insert into CRYSTAL_INFO(LAST_UNIQUE_ID) values (1);

