#### This is for string "screeningParameters".
#### The purpose is to create virtual attribute "dirOK".

package provide DCSScreeningParameters 1.0  

package require DCSString

class DCS::ScreeningParameters {
	inherit DCS::String

	public method setContents
	public method configureString

    public method getDirOK { } {
        set dir [lindex $_contents 2]
        set eList [file split $dir]
        foreach e $eList {
            if {[string equal -nocase $e username]} {
                return 0
            }
        }
        return 1
    }

	constructor { args } {
	    # call base class constructor
	    ::DCS::Component::constructor { \
		    contents { getContents } \
            dirOK { getDirOK } \
		 }
	} {
        ###following are the old fields generated by robotDHS
        createAttributeFromField directory 2

		eval configure $args
		announceExist
	}
}
body DCS::ScreeningParameters::configureString { message_ } {
    #puts "ScreeningParameters: config $message_"

	configure -controller  [lindex $message_ 2] 
	set contents [lrange $message_ 3 end]

    setContents normal $contents
}

body DCS::ScreeningParameters::setContents { status_ contents_ } {
    #puts "ScreeningParameters setContents: $status_ $contents_"
    set lastResult $status_
    if {$lastResult == "normal"} {
        set _contents $contents_
	    #inform that new configuration is available
	    updateRegisteredComponents contents
	    updateRegisteredComponents dirOK

	    updateRegisteredFieldListeners
    }

	recalcStatus
}
