GET /gateway/servlet/SessionStatus;jsessionid=CE0C8B3F38599FA28D0310C2FC0C69A8?AppName=SMBTest&ValidBeamlines=True HTTP/1.1
User-Agent: Java1.3.1
Host: smb.slac.stanford.edu:8180
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive

