GET /copyFile?impOldFilePath=/data/blctl/BL9-1/test12_40_05.img&impNewFilePath=/data/jsong/impTest/file&impUser=blctl&impSessionID=F20D268423823AB74082F31E01D1F545&impBackupExist=true&impCreateParents=true HTTP/1.1




