POST /copyFile?impOldFilePath=MULTIPLE_IN_BODY&impUser=blctl&impSessionID=11619765C8D97CC2A7BE13CEBCE39CDD HTTP/1.1
Host: smbdev3:61002
Content-Type: text/plain
Content-Length: 154

impOldFilePath=/home/blctl/imperson impNewFilePath=/data/blctl/tmp/fff1
impOldFilePath=/home/blctl/update_bluice_spec impNewFilePath=/data/blctl/tmp/fff2
