GET /getImage?impFilePath=/data/penjitk/dataset/pseudomad/myo3_4_E1_001.img&impSizeX=400&impSizeY=400&impPercentX=0.5&impPercentY=0.5&impGray=1000&impZoom=1.0&impUser=penjitk&impSessionID=1C3F5963D7A107907F2D95F4E40F19D3 HTTP/1.1





