POST /writeFile?impFilePath=/data/blctl/impTest/FF1/FF2/FF3/FF4/file&impUser=blctl&impSessionID=46D057CFBE7924D53F79BC03E8A1F7A7&impAppend=true&impBackupExist=true HTTP/1.1
Content-Type: text/plain
Content-Length: 30

123456789012345678901234567890

