dos2unix log_manager.c    log_manager.c          
dos2unix log_xml_formatter.c log_xml_formatter.c
dos2unix log_common.h      log_common.h        
dos2unix log_manager.h       log_manager.h     
dos2unix log_xml_formatter.h log_xml_formatter.h
dos2unix log_xml_formatter.h log_xml_formatter.h
dos2unix log_quick.c     log_quick.c          
dos2unix logger.c   logger.c
dos2unix log_console_handler.h   log_console_handler.h  
dos2unix log_quick.h             log_quick.h 
dos2unix logger.dtd   logger.dtd
dos2unix log_file_handler.c    log_file_handler.c    
dos2unix log_record.c   log_record.c          
dos2unix logger.h   logger.h
dos2unix log_file_handler.h      log_file_handler.h     
dos2unix log_record.h        log_record.h         
dos2unix logging.h  logging.h
dos2unix log_filter.c    log_filter.c          
dos2unix log_simple_formatter.c  log_simple_formatter.c  
dos2unix logsystem.dtd  logsystem.dtd
dos2unix log_filter.h         log_filter.h         
dos2unix log_simple_formatter.h  log_simple_formatter.h  
dos2unix logsystem.xml   logsystem.xml
dos2unix log_formatter.c      log_formatter.c       
dos2unix log_socket_handler.c    log_socket_handler.c   
dos2unix makefile  makefile
dos2unix log_formatter.h         log_formatter.h      
dos2unix log_socket_handler.h    log_socket_handler.h  
dos2unix log_handler.c         log_handler.c        
dos2unix log_token_formatter.c   log_token_formatter.c  
dos2unix test.c  test.c
dos2unix log_handler.h     log_handler.h         
dos2unix log_token_formatter.h   log_token_formatter.h   
dos2unix test_log_formatter.c  test_log_formatter.c
dos2unix log_handler_factory.c   log_handler_factory.c   
dos2unix log_trace_formatter.c   log_trace_formatter.c   
dos2unix test_log_level.c  test_log_level.c
dos2unix log_handler_factory.h   log_handler_factory.h   
dos2unix log_trace_formatter.h   log_trace_formatter.h   
dos2unix test_log_record.c  test_log_record.c
dos2unix log_level.c     log_level.c           
dos2unix log_udp_handler.c     log_udp_handler.c     
dos2unix test_logger.c   test_logger.c
dos2unix log_level.h      log_level.h         
dos2unix log_udp_handler.h     log_udp_handler.h    
dos2unix test_quick.c   test_quick.c


