select max(CASSETTE_ID) from CTS_CASSETTE;


		select
			CTS_CASSETTE.CASSETTE_ID, CTS_USER.LOGIN_NAME, CTS_CASSETTEFILE.FILE_ID,  CTS_CASSETTEFILE.FILENAME, 
			CTS_CASSETTEFILE.UPLOAD_FILENAME, CTS_CASSETTEFILE.UPLOAD_TIME
		from 
			CTS_CASSETTE, CTS_USER, CTS_CASSETTEFILE
		where
			CTS_USER.LOGIN_NAME = 'jcsg' and
			CTS_CASSETTE.USER_ID = CTS_USER.USER_ID and
			CTS_CASSETTEFILE.FILE_ID in (
				select max(CTS_CASSETTEFILE.FILE_ID) from CTS_CASSETTEFILE where CTS_CASSETTEFILE.CASSETTE_ID = CTS_CASSETTE.CASSETTE_ID
			)	
			
		order by CASSETTE_ID;	
			
			
select * from CTS_CASSETTEFILE where CTS_CASSETTEFILE.CASSETTE_ID = 15235;

select * from CTS_CASSETTE, CTS_USER where CTS_USER.LOGIN_NAME = 'penjitk' and CTS_USER.USER_ID = CTS_CASSETTE.USER_ID order by CASSETTE_ID;

select * from CTS_USER where LOGIN_NAME = 'penjitk';
