#Main Sconscript for the ---dcsconfig--- module
# An experimental build system used at LBNL (Nick Sauter) to compile the SSRL
# packages for WebIce.  Build tools include SCons & cctbx, not gmake.

import libtbx.load_env
import os
Import("env_base", "env_etc")

env_etc.dcsconfig_dist = libtbx.env.dist_path("dcsconfig")

env_etc.dcsconfig_include = env_etc.norm_join(env_etc.dcsconfig_dist,"src")
env_etc.dcsconfig_common_includes = [
  env_etc.dcsconfig_include,
  env_etc.xos_cpp_include,
  env_etc.logging_include,
  env_etc.xos_include,
]

env = env_base.Copy(
  CXXFLAGS=env_etc.cxxflags_base,
  SHCXXFLAGS=env_etc.cxxflags_base,
  SHLINKFLAGS=env_etc.shlinkflags,
)

env_etc.include_registry.append(
  env=env,
  paths=env_etc.dcsconfig_common_includes)

env_dcsconfig = env.Copy(
  LIBS = env_etc.libm + ["rt","pthread","c"],
)

arch_dependent_flags={"irix_CC":["-DIRIX","-DPTHREADS","-MP:dsm=off"],
                      "unix_gcc":["-DLINUX","-fexceptions","-pthread"], 
                      "tru64_cxx":["-DDEC_UNIX","-pthread"]}

env_dcsconfig.Append(
CXXFLAGS=["-c","-D_REENTRANT"]+arch_dependent_flags[env_etc.compiler])

env_dcsconfig.Append(LIBPATH=["#lib",])

lib_dcsconfig_sources = [
  "src/DcsConfig.cxx",
  "src/LogConfig.cxx",
]

builder = env_dcsconfig.StaticLibrary
builder(
    target="#lib/dcsconfig",
    source=lib_dcsconfig_sources,
)
