/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jpam_Pam */

#ifndef _Included_net_sf_jpam_Pam
#define _Included_net_sf_jpam_Pam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jpam_Pam
 * Method:    isSharedLibraryWorking
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_jpam_Pam_isSharedLibraryWorking
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jpam_Pam
 * Method:    authenticate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jpam_Pam_authenticate
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
