// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "spelcomctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CSpelcomctrl1

IMPLEMENT_DYNCREATE(CSpelcomctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSpelcomctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CSpelcomctrl1 operations
